// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD96HGb7UhWL7kTCQXj-dYu-_7yqRzQSGw',
    appId: '1:257664340444:android:acc6c34f17d010b0',
    messagingSenderId: '257664340444',
    projectId: 'stalker-a01a3',
    databaseURL: 'https://stalker-a01a3.firebaseio.com',
    storageBucket: 'stalker-a01a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz7jXkpH7-YzUrVg9FpLTA9oNB6Z5C9lM',
    appId: '1:257664340444:ios:596d050f3686a8e2deff19',
    messagingSenderId: '257664340444',
    projectId: 'stalker-a01a3',
    databaseURL: 'https://stalker-a01a3.firebaseio.com',
    storageBucket: 'stalker-a01a3.appspot.com',
    androidClientId: '257664340444-d9dj9n0hc8mogt97vnoo5tefkuml17me.apps.googleusercontent.com',
    iosClientId: '257664340444-mgukqua690d20ru319q92uj6u81290jb.apps.googleusercontent.com',
    iosBundleId: 'gartz.stalker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz7jXkpH7-YzUrVg9FpLTA9oNB6Z5C9lM',
    appId: '1:257664340444:ios:596d050f3686a8e2deff19',
    messagingSenderId: '257664340444',
    projectId: 'stalker-a01a3',
    databaseURL: 'https://stalker-a01a3.firebaseio.com',
    storageBucket: 'stalker-a01a3.appspot.com',
    androidClientId: '257664340444-d9dj9n0hc8mogt97vnoo5tefkuml17me.apps.googleusercontent.com',
    iosClientId: '257664340444-mgukqua690d20ru319q92uj6u81290jb.apps.googleusercontent.com',
    iosBundleId: 'gartz.stalker',
  );
}
